/*
   This file was generated automatically by Alchitry Labs version 1.1.2.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     WIDTH = 5
*/
module encoder_2 (
    input [4:0] in,
    output reg [2:0] out
  );
  
  localparam WIDTH = 3'h5;
  
  
  integer i;
  
  always @* begin
    out = 1'bx;
    for (i = 1'h0; i < 3'h5; i = i + 1) begin
      if (in[(i)*1+0-:1]) begin
        out = i;
      end
    end
  end
endmodule
